for i in [1,2,3,4,5]:
    print(i)
    for j in [1,2,3,4,5]:
        print(j)
        print(i + j)
    print(i)
print("done looping")

'''
1   i=1 print(i)
1   j=1 print(j)
2   print(i+j)
2   j=2 print(j)
3   print(i+j)
3   j=3 print(j)
4   print(i+j)
4   j=4 print(j)
5   print(i+j)
5   print(j)
6   print(i+j)
1   print(i)        # 가장 안쪽에 있는 for문이 첫번째 반복이 끝나서 print(i)    
2   i=2 print(i)
1   j=1 print(j)
3   print(i+j)
2   j=2 print(j)
4   print(i+j)
3   j=3 print(j)
5   print(i+j)
4   j=4 print(j)
6   print(i+j)
5   j=5 print(j)
7   print(i+j)      
2   print(i)         # 가장 안쪽에 있는 for문 두번째 반복 끝
3   i=3 print(i)
1   j=1 print(j)
4   print(i+j)
2   j=2 print(j)
5   print(i+j)
3   j=3 print(j)
6   print(i+j)
4   j=4 print(j)
7   print(i+j)
5   j=5 print(j)
8   print(i+j)
3   print(i)        # 가장 안쪽에 있는 for문 세번째 반복 끝        
4   i=4
1   j=1 print(j)
5   print(i+j)
2   j=2 print(j)
6   print(i+j)
3   j=3 print(j)
7   print(i+j)
4   j=4 print(j)
8   print(i+j)
5   j=5 print(j)
9   print(i+j)
4   print(i)        # 가장 안쪽에 있는 for문 네번째 반복 끝
5   i=5 print(i)
1   j=1 print(j)
6   print(i+j)
2   j=2 print(j)
7   print(i+j)
3   j=3 print(j)
8   print(i+j)
4   j=4 print(j)
9   print(i+j)
5   j=5 print(j)
10  print(i+j)
5   i=5             # 가장 안쪽에 있는 for문 다섯번째 반복 끝. 최종
'''
